default_stages: [pre-push]  # CRITICAL: Run hooks on push, not commit

repos:
  # Basic file checks (these can run on commit for quick feedback)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        stages: [pre-commit]
      - id: end-of-file-fixer
        stages: [pre-commit]
      - id: check-yaml
        stages: [pre-commit]
      - id: check-added-large-files
        stages: [pre-commit]
      - id: check-json
        stages: [pre-commit]
      - id: check-toml
        stages: [pre-commit]
      - id: check-merge-conflict
        stages: [pre-commit]
      - id: debug-statements
        stages: [pre-commit]
      - id: mixed-line-ending
        stages: [pre-commit]

  # Tests must pass before push
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: uv run python -m pytest tests/unit -q --tb=short
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
        stages: [pre-push]

  # Linting (NO auto-fix - fail on issues) - runs on push
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.7
    hooks:
      - id: ruff
        name: ruff-lint
        args: [--no-fix]  # CRITICAL: No auto-fix, fail on issues
        stages: [pre-push]
      - id: ruff-format
        name: ruff-format
        args: [--check]   # CRITICAL: Check only, don't auto-format
        stages: [pre-push]

  # Type checking (disabled for now due to codebase type issues)
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.8.0
  #   hooks:
  #     - id: mypy
  #       name: mypy-type-check
  #       additional_dependencies:
  #         - pydantic>=2.5.0
  #         - types-aiofiles
  #         - types-pyyaml
  #       args: [--config-file, pyproject.toml, --no-strict-optional, --ignore-missing-imports]
  #       exclude: ^(tests/|examples/)

  # Import sorting (check only) - runs on push
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort-check
        args: [--profile, black, --line-length, "120", --check-only, --diff]
        stages: [pre-push]

  # Code formatting (check only) - runs on push
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        name: black-check
        args: [--line-length, "120", --check, --diff]
        stages: [pre-push]
