name: CI / Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint:
    name: Lint & Type Check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Set up Python 3.13
      run: uv python install 3.13

    - name: Cache Python packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/uv
          .venv
        key: ${{ runner.os }}-python-3.13-${{ hashFiles('uv.lock') }}
        restore-keys: |
          ${{ runner.os }}-python-3.13-
          ${{ runner.os }}-python-

    - name: Install dependencies
      run: uv sync --all-extras --dev

    - name: Run linting
      run: |
        uv run ruff check .
        uv run ruff format --check .

    - name: Run type checking
      run: uv run mypy src/pantainos --ignore-missing-imports --no-error-summary || echo "Type checking issues found - continuing for now"
